### ISSUE TITLE
Add support for greyscale images instead of RGB

### ISSUE THREAD

**Issue by FMalerba** [hpi-www-midl-text-localization/dataset-generator#26]

**Comment by bakoe** [comment]
@FMalerba Didn't we agree on filtering the images in the _text-localization-agent_ during import (for **training** only) instead of making the _dataset-generator_ create grayscale images? 

See [our meeting protocol](https://github.com/hpi-www-midl-text-localization/meeting-protocols/wiki/10.12.18-First-full-learning-pass;-future-steps-regarding-more-intense-training) for additional info:

> Switch from RGB to grayscale images (for the training; the testing process should probably involve RGB images as well)

This would mean that this issue (in the _dataset-generator_ project) could be closed and we should create a corresponding issue in the _text-localization-agent_ project. What do you think, does this make sense? Sorry for any confusion caused!

**Comment by FMalerba** [comment]
Ups I understood that we were gonna feed greyscale images for training and then test with colour images (filtering them). Because I thought we would (in some far future) test with external datasets and simply filter the images before giving them to the agent. It is obviously the same to just produce coloured images and tell the agent to filter them... Though maybe doesn't it make more sense if the environment transformes them to greyscale instead of the agent?

**Comment by FMalerba** [comment]
Also, if we have the images transformed to greyscale I would change the code with the "W3C recommended version" of contrast that I have also done (but not commited to the branch), since it might ensure better contrast after filtering. The reason for this is that the current contrast check basically looks at "color difference", but not at luminance. Since what we are then interested in is contrast in the greyscale, I believe that the luminance-based approach is better than the color difference

**Comment by bakoe** [comment]
> Ups I understood that we were gonna feed greyscale images for training and then test with colour images (filtering them). Because I thought we would (in some far future) test with external datasets and simply filter the images before giving them to the agent.

Actually that's exactly how I understood it as well! 😆 Since the dataset-generator is (in my opinion) really only about creating synthetic training data (and not about e. g. filtering existing real-world data for further usage in the RL process), I thought that it may not the best place to do the grayscale-filtering here.

> maybe doesn't it make more sense if the environment transformes them to greyscale instead of the agent?

Yeah, good question! I guess this depends a bit on how much knowledge the environment has about whether it's used for training or for testing at the moment. Since currently neither our environment [nor the environments provided by OpenAI](https://github.com/search/advanced?q=test+train+path%3A%2Fgym%2Fgym%2Fenvs%2F+repo%3Aopenai%2Fgym) contain "test" or "train" anywhere in their code, I'd guess that the logic regarding "testing" or "training" phase should belong into the agent (or the code setting up the agent and the environment), which would currently be _text-localization-agent_ (although the project name maybe isn't optimal). Thus, I'd prefer to put the image filtering (grayscale conversion) there, at least for the moment.

**Comment by bakoe** [comment]
> Also, if we have the images transformed to greyscale I would change the code with the "W3C recommended version" of contrast that I have also done (but not commited to the branch), since it might ensure better contrast after filtering. The reason for this is that the current contrast check basically looks at "color difference", but not at luminance. Since what we are then interested in is contrast in the greyscale, I believe that the luminance-based approach is better than the color difference

Yeah, absolutely! Good idea! I'd as also prefer using luminance for ensuring a minimum contrast. 👍
